// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Base/Card/index.vue')['default']
    Category: typeof import('./src/components/Base/Category/index.vue')['default']
    CategoryList: typeof import('./src/components/Base/Home/CategoryList.vue')['default']
    Footer: typeof import('./src/components/Base/Footer/index.vue')['default']
    HomeNewsGroup: typeof import('./src/components/Base/Home/HomeNewsGroup.vue')['default']
    MustReadSection: typeof import('./src/components/Index/MustReadSection.vue')['default']
    Navbar: typeof import('./src/components/Base/Navbar/index.vue')['default']
    NewsItem: typeof import('./src/components/Base/NewsItem/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TrendingSection: typeof import('./src/components/Index/TrendingSection.vue')['default']
    Welcome: typeof import('./src/components/Base/Home/Welcome.vue')['default']
  }
}
